### ISSUE TITLE
Help :  GlobalKey<NavigatorState> was used multiple times  error.

### ISSUE THREAD

**Issue by volkangurol** [bizz84/nested-navigation-demo-flutter#5]
Thanks for great example @bizz84 . I used in my projects without any problem so far.
But i stuck in one point. If you can help, i really appreciate it.
I wanted to integrate Firebase Analytics in my project to logging events. 

`static FirebaseAnalytics analytics = FirebaseAnalytics();
  static FirebaseAnalyticsObserver observer =
  FirebaseAnalyticsObserver(analytics: analytics);`

In MaterialApp i put observer,  I reliazed that analytics not logging. If i remove tabbar completely it works. Then i found that if i pass observer param to Navigator page you defined, it works for first page but when i switch between tabs  i get GlobalKey<NavigatorState>  used multiple times  error.

How can we call GlobalKey<NavigatorState> once ?

<img width="773" alt="Screen Shot 2019-06-09 at 08 01 21" src="https://user-images.githubusercontent.com/2510054/59155198-ccf25980-8a8c-11e9-8b76-5064411d7149.png">

**Comment by Shanmukhabhargav** [comment]
Hi @volkangurol need to place the observer in the topmost MaterialApp and that will help to reduce the issue of generating the GlobalKey for multiple times.

**Comment by volkangurol** [comment]
> Hi @volkangurol need to place the observer in the topmost MaterialApp and that will help to reduce the issue of generating the GlobalKey for multiple times.

Thanks this was an old issue. I switched to cupertinopagescaffold and as you stated, defined global key in the top most solved my issue
